# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-12 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spiderkeyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=100)),
                ('keyWordNum', models.IntegerField()),
                ('modifiedTime', models.CharField(max_length=50)),
                ('startTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'spiderKey',
            },
        ),
        migrations.CreateModel(
            name='taskTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('taskCreateDate', models.DateTimeField()),
                ('subscribeStatus', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pushTask',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('registerStatus', models.IntegerField(default=0)),
                ('sendEmailRandom', models.CharField(default='', max_length=60)),
                ('successCreateTime', models.DateTimeField(default=datetime.datetime(2018, 5, 12, 17, 9, 4, 313564))),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='tasktable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
